version: 2

sources:
  - name: gz_raw_data AS raw
    description: raw data for finance team
    tables:
      - name: raw_gz_sales AS sales
        description: sales information

      - name: raw_gz_product AS product
        description: product information

      - name: raw_gz_ship AS ship
        description: shipping information
