version: 2

sources:
  - name: gz_raw_data
    description: raw data for finance team
    tables:
      - name: raw_gz_sales
        identifier: raw_gz_sales
        description: information, one row per product_id found in orders_id.
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
          - not_null:
              column_name: "(orders_id || '_' || pdt_id)"
        columns:
          - name: date_date
            description: the date of purchase

          - name: orders_id
            description: id of each orders

          - name: pdt_id
            description: id of each product in each order

          - name: revenue
            description: total cost per specific product or products

          - name: quantity
            description: amount of each product in the order

      - name: raw_gz_product
        identifier: raw_gz_product
        description: product information
        columns:
          - name: products_id
            description: Primary key of the table
            tests:
              - unique
              - not_null

          - name: purchase_price
            description: Cost per product

      - name: raw_gz_ship
        identifier: raw_gz_ship
        description: shipping information
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: Cost of shipping for the customer

          - name: log_cost
            description: Logistics cost for Greenweez

          - name: ship_cost
            description: Shipping cost for Greenweez

      - name: raw_gz_adwords
        identifier: raw_gz_adwords
        description: adwords advertising campaign data
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
          - not_null:
              column_name: "(date_date || '_' || campaign_key)"

      - name: raw_gz_bing
        identifier: raw_gz_bing
        description: bind advertising campaign data
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
          - not_null:
              column_name: "(date_date || '_' || campaign_key)"

      - name: raw_gz_criteo
        identifier: raw_gz_criteo
        description: criteo advertising campaign data
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
          - not_null:
              column_name: "(date_date || '_' || campaign_key)"
      - name: raw_gz_facebook
        identifier: raw_gz_facebook
        description: facebook advertising campaign data
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
          - not_null:
              column_name: "(date_date || '_' || campaign_key)"
      - name: stg_raw_adwords
        identifier: stg_raw_adwords
        description: cleaned adwords data

      - name: stg_raw_bing
        identifier: stg_raw_bing
        description: cleaned bing data

      - name: stg_raw_criteo
        identifier: stg_raw_adwords
        description: cleaned adwords data

      - name: stg_raw_facebook
        identifier: stg_raw_facebook
        description: cleaned facebook data


models:
    - name: int_sales_margin
      description: sales info for each product

    - name: int_orders_margin
      description: sales data with margin calculated

    - name: int_orders_operational
      description: sales data with logisitics and shipping include

    - name: int_campaigns
      description: all advertising campaign data collated from adwords, bing, criteo and facebook
      columns:
        - name: paid_source
          description: paid advertising source
          tests:
            - accepted_values:
                values: ['Facebook', 'Criteo', 'Bing', 'Adwords']

    - name: int_campaigns_day
      description: all advertising campaign data aggregated per day

    - name: finance_days
      description: daily financial summary

    - name: finance_campaigns_day
      description: daily financial summary including advertising margin

