version: 2

sources:
  - name: gz_raw_data
    description: raw data for finance team
    tables:
      - name: raw_gz_sales
        description: sales information

      - name: raw_gz_product
        description: product information

      - name: raw_gz_ship
        description: shipping information
