version: 2

sources:
  - name: gz_raw_data
    description: raw data for finance team
    tables:
      - name: raw_gz_sales
        identifier: raw_gz_sales
        description: information, one row per product_id found in orders_id.
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: date_date
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
          - not_null:
              column_name: "(orders_id || '_' || pdt_id)"
        columns:
            - name: date_date
              description: the date of purchase
            
            - name: orders_id
              description: id of each orders
            
            - name: pdt_id
              description: id of each product in each order

            - name: revenue
              description: total cost per specific product or products

            - name: quantity
              description: amount of each product in the order

      - name: raw_gz_product
        identifier: raw_gz_product
        description: product information
        columns:
            - name: products_id
              description: Primary key of the table
              tests:
                - unique 
                - not_null
            
            - name: purchase_price
              description: Cost per product
                

      - name: raw_gz_ship
        identifier: raw_gz_ship
        description: shipping information
        columns:
          - name: orders_id
            description: Primary key of the table
            tests:
              - unique
              - not_null

          - name: shipping_fee
            description: Cost of shipping for the customer
          
          - name: log_cost
            description: Logistics cost for Greenweez

          - name: ship_cost
            description: Shipping cost for Greenweez